# Generated by Django 4.2.3 on 2023-11-04 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('older', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='photos_uuid',
            new_name='photo_files',
        ),
        migrations.AddField(
            model_name='person',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='family_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='family_phone',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='lost_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
